# Generated by Django 3.0.6 on 2020-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200604_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='body',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
