# Generated by Django 3.0.6 on 2020-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20200610_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRI', 'Private')], default='PRI', max_length=100),
        ),
    ]
