# Generated by Django 3.0.6 on 2020-06-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_snippet_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tags',
            new_name='tag_names',
        ),
    ]
