# Generated by Django 3.0.6 on 2020-06-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20200612_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tag_names',
            new_name='tags',
        ),
    ]
